### ISSUE TITLE
Améliorations prévues pour la campagne 2018-2019

### ISSUE THREAD

**Issue by Morendil** [betagouv/dossiersco#102]
- [ ] Dédoublonner les responsables légaux
- [ ] Permettre aux familles d'adresser un message à l'établissement
- [ ] Investiguer dans quelles conditions on peut/doit ajouter ou supprimer un responsable légal
- [ ] Adopter les règles typographiques françaises
- [ ] Gérer l'adhésion au FSE (foyer socio-éducatif) suggestion Tillion
- [ ] Générer les formulaires infirmerie préremplis, à diffuser par le collège ou imprimer
- [ ] Gérer l'inscription; ingérer un fichier Affelnet
- [ ] tarif de cantine uniquement pour paris, fonctionnement différent pour les autres académies
- [ ] Prise en charge de la génération du PDF parents dans l'appli
- [ ] Pouvoir générer les invitations PDF d'une classe entière
- [ ] Invitation parents (PDF): afficher la date en français
- [ ] Invitation parents (PDF): afficher le nom et le "pourquoi" des PJ
- [ ] Invitation parents (PDF): afficher la date limite de la démarche
- [ ] Invitation parents (PDF): reprendre la bonne URL
- [ ] Invitation parents (PDF): rendre la phrase d'intro du message de permanence plus générique
- [ ] Invitation parents (PDF): se rapprocher, notamment avec logo Académie de Paris inclus, de la version GDoc
- [ ] Invitation parents (PDF): préciser que l'identifiant est spécifique à l'élève concerné (l'identifiant de XXX est)
- [ ] Invitation parents (PDF): préciser le format de la date
- [ ] Notifier la famille des options pédagogiques affectées (Tillion)
- [ ] Fournir une version papier de la liste des élèves avec une attestation d'assurance (emplacement potentiel : dans l'onglet export) (Demande de Tillion)
- [ ] Mettre un scanner de virus  sur les PJs http://www.clamav.net

**Comment by LucienMLD** [comment]
Repris dans le backlog avec l'équipe (https://github.com/betagouv/dossiersco/projects/1)
