### ISSUE TITLE
Inscrire à la cantine avec tarification QF

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/dossiersco#170]
Irritant important pour l'intendance

### Process actuel (papier) : 
Le Département de Paris (service DASCO) obtient de la CAF les QF des collégiens, envoie la notification aux familles par courrier postal. Les collèges demandent copie de la notification au  moment de l'inscription. Conséquence négative pour les familles : application du tarif de cantine le plus élevé, en l'absence de notification. Pour les agents : relances fastidieuses pour obtenir le QF, puis pour le recouvrement des créances.

### Process DossierSCO 2018 : la famille télécharge la notification par smartphone. Questions non réglées :
- l'irritant des avis manquants demeure
- l'intendance voit un double flux de notifications (papier et photo sur dossierSCO). Comment simplifier  ?

### Process par API particulier
Après autorisation par la DINSIC, APIpart donne un token a l'établissement qui permet de consulter les QF des familles, avec l'identifiant CAF préalablement récupéré sur DossierSCO.

- [x] demander l'accès à l'API pour lycée Arago
- [ ] préparer convention entre EPLE et APIpart
- [ ] tester avec une famille
- [ ] industrialiser

- [x] Contact Emmanuel GREGOIRE, via Henri et Thomas CAZENAVE, voir mail de février 18
- [ ] API particulier : tester un élève avec Anna Livia
- [ ] Vu au stand up du 14/11/18 deux chefs de projet : yvan.michel@paris.fr et baptiste.gabourin@paris.fr

**Comment by Pierre2Maulmont** [comment]
Demande d'autorisation d'accès à APIpart, pour le lycée ARAGO, postée le 13/1/19. Attente de la réponse du Pole juridique de la DINSIC.

**Comment by Pierre2Maulmont** [comment]
Contact pris avec 1er adjoint à la maire de Paris
Objectif : constituer un plan B pour récupérer directement les QF des familles, si autorisation d'accès des collèges par APIpart s'avérait trop compliquée
