### ISSUE TITLE
Convoquer les parents sur DossierSCO

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/dossiersco#177]
Générer un PDF avec les informations nécessaires à la connexion sur DossierSCO.

Pouvoir générer les invitations PDF d'une classe entière
Invitation parents (PDF): afficher la date en français
Invitation parents (PDF): afficher le nom et le "pourquoi" des PJ
Invitation parents (PDF): afficher la date limite de la démarche
Invitation parents (PDF): reprendre la bonne URL
Invitation parents (PDF): rendre la phrase d'intro du message de permanence plus générique
Invitation parents (PDF): se rapprocher, notamment avec logo Académie de Paris inclus, de la version GDoc
Invitation parents (PDF): préciser que l'identifiant est spécifique à l'élève concerné (l'identifiant de XXX est)
Invitation parents (PDF): préciser le format de la date

**Comment by Pierre2Maulmont** [comment]
On peut voir un [exemplaire de convocation](https://drive.google.com/drive/u/1/folders/1duO_hUmOdjbe91wMB8n5hhi4fhkxM-Y-) dans le répertoire Googledrive/DossierSCO/5 - Etablissements clients
