### ISSUE TITLE
Vérifier l'utilisation de rack_ssl_enforcer

### ISSUE THREAD

**Issue by yaf** [betagouv/dossiersco#188]
Cette gem était installée sur la version Sinatra. Pour passer à Rails, elle a été désactivée. Il serait bon de vérifier comment savoir si elle fonctionne, si elle est utile, et selon les cas, la re-installer.

**Comment by krichtof** [comment]
Cette  gem a été utilisée sur Sinatra pour forcer SSL. https://github.com/betagouv/dossiersco/commit/63c1a515f92bd3b8074cf09f4eb3007e9f48127f

Rails permet de forcer SSL.
Inutile d'utiliser cette gem depuis #301
