### ISSUE TITLE
Migrer sur Scalingo

### ISSUE THREAD

**Issue by yaf** [betagouv/dossiersco#191]
Afin de passer par un hébergeur français, et un datacenter sur le territoire français, une migration sur Scalingo serait nécessaire.

**Comment by yaf** [comment]
https://dossiersco.scalingo.io/

Reste à installer un deploiement automatique sur staging et gérer la prod.

**Comment by Pierre2Maulmont** [comment]
penser à vérifier les envois de mail

**Comment by yaf** [comment]
la partie staging est transformer en demo sur dossiersco.scalingo.io. Demande effectué pour avoir un demo.dossiersco.beta.gouv.fr qui pointe dessus.

**Comment by yaf** [comment]
Suite à quelques difficulté pour installer ce qu'il faut dans circleci pour faire un déploiement à partir de ce dernier, j'ai branché scalingo sur le github pour avoir un déploiement automatique....

**Comment by krichtof** [comment]
- [ ] Ajout de la CB sur scalingo
- [ ] Création environnement prod
- [ ] Création branche de prod
- [ ] Migration des données
