### ISSUE TITLE
Utiliser LetterOpener sur staging

### ISSUE THREAD

**Issue by yaf** [betagouv/dossiersco#196]
Afin de pouvoir vérifier les emails sur staging, ça serait bien d'ajouter un letter opener.

**Comment by pblayo** [comment]
@yaf : il s'agit de vérifier les emails entrants ou sortants ?

**Comment by yaf** [comment]
Sortant.

**Comment by LucienMLD** [comment]
Commits liés 783d5dd, ea1373c, b71a598
