### ISSUE TITLE
Ajouter un élève dans siecle

### ISSUE THREAD

**Issue by Pierre2Maulmont** [betagouv/dossiersco#201]
Générer un export XML pour import dans siecle, concernant un nouvel élève

**Comment by Pierre2Maulmont** [comment]
exporter les données vers SIECLE, par la fenêtre de l'import privé.
Environnement de test mis à disposition par Lucien LECLERC (CPN Scolarité 2D
DNE B2-1), avec obligation d'utiliser un EPLE de l'académie de Lille.

**Comment by yaf** [comment]
Aujourd'hui, nous pouvons faire une page qui exporte un fichier XML

Nous ne savons pas quel format utiliser... Est-il possible d'obtenir un fichier exemple ? Un fichier qu'un établissement privée utilise ?

**Comment by yaf** [comment]
Voir dans https://github.com/betagouv/dossiersco/tree/production/doc/import_prive

**Comment by krichtof** [comment]
@yaf @LucienMLD Pour générer un fichier xml qui sera importé dans siecle, il semble qu'il faille utiliser : https://github.com/betagouv/dossiersco/blob/production/doc/import_prive/schema_Import_3.0.xsd

2 documents peuvent aider à générer le fichier xml : 

- https://github.com/betagouv/dossiersco/blob/production/doc/import_prive/regles_gestion_bee.pdf
- https://github.com/betagouv/dossiersco/blob/production/doc/import_prive/spec_import.pdf

Quelques informations complémentaires : 
- A noter que l'ID_NATIONAL correspond à l'INE de l'élève.
- Attention : contrairement à ce qui est indiqué dans la documentation ``regles_gestion_bee.pdf``, le CODE_PARENTE doit contenir 2 caracteres
  - 01 (PERE)
  - 02 (MERE)
  - 03 (TUTEUR)

**Comment by yaf** [comment]
Je suis conscient qu'il reste le test siecle à faire.

Je clos le ticket et le laisse dans la colonne en court dans le suivi projet, histoire de distinguer....

**Comment by yaf** [comment]
Contexte : en prod, sur lycée Arago, import de l'extraction aujourd'hui.

    Modification en tant que famille de l'adresse mail des responsables légaux d'un élève.
    Validation jusqu'au bout de l'inscription.
    Export xml du lycée Arago. Import du xml dans SIECLE

![56353308-66119c00-61d1-11e9-832a-a52525003626](https://user-images.githubusercontent.com/42057/56365072-55245300-61f0-11e9-8a34-8de1cbcc0842.png)
