### ISSUE TITLE
Modifier un élève dans siecle 

### ISSUE THREAD

**Issue by Pierre2Maulmont** [betagouv/dossiersco#202]
Générer un fichier XML pour import dans siecle, concernant un élève existant.

- [ ] Changement d'adresse ?
- [ ] Changment d'option ?
- [ ] ?

**Comment by Pierre2Maulmont** [comment]
exporter les données vers SIECLE, par la fenêtre de l'import privé.
Environnement de test mis à disposition par Lucien LECLERC (CPN Scolarité 2D
DNE B2-1), avec obligation d'utiliser un EPLE de l'académie de Lille.

**Comment by yaf** [comment]
duplicate #201 
Ajouter ou modifier un élève dans SIECLE, c'est la même chose niveau code de notre coté : on produit un fichier XML dans les deux cas.
