### ISSUE TITLE
Changer de format pour les imports (et exports ?)

### ISSUE THREAD

**Issue by yaf** [betagouv/dossiersco#210]
Demande si l'académie peut fournir des fichiers à un format ouvert (type xml ou ods) au lieu du fichier Excel (xls, format propriétaire)

**Comment by Pierre2Maulmont** [comment]
A fusionner avec Demander aux familles de s'inscrire en 6ème #198
Demande à faire au contact DSI Affelnet Paris
Pour les niveaux 5, 4 et 3ème, on a des xml
