### ISSUE TITLE
upload des pièces jointes avec le framework

### ISSUE THREAD

**Issue by yaf** [betagouv/dossiersco#234]
Pour simplifier la configuration (et limiter le nombre de librairie que nous utilisons), et puisque depuis la version 5 de Ruby On Rails on accède à un objet `active_storage`, ça semble intéressant de revoir cette partie avec la [configuration proposé dans le guide de Ruby On Rails](https://edgeguides.rubyonrails.org/active_storage_overview.html)

**Comment by krichtof** [comment]
- https://github.com/betagouv/dossiersco/commit/4746a261d6600f5ba1171635df3ce164a5a277ac
- https://github.com/betagouv/dossiersco/commit/2fb52e96ec716e267731256939deec0b57a4c455
- https://github.com/betagouv/dossiersco/commit/dff894d5916a6fc85149843802dd25aff371b6d2
- https://github.com/betagouv/dossiersco/commit/fc881cd622d94e6d86f03e27aa7cf230d2880c6f
- https://github.com/betagouv/dossiersco/commit/ce24249ac73d62b2edfe64c58ad8176a5cf334f0
- https://github.com/betagouv/dossiersco/commit/d37c5ce4453f604165fea170517c723269beba4a
- https://github.com/betagouv/dossiersco/commit/8efc48f49b34860e3db566d0d742b8675f71a2bb
