### ISSUE TITLE
récupérer les documents de prod de l'année dernière (sur s3)

### ISSUE THREAD

**Issue by yaf** [betagouv/dossiersco#256]
Suite
- à la migration rails
- à la mise en place d'active_storage

nous ne pourrons plus consulter les anciennes pièces jointes.

Il faudrait :
- [x] les archiver
- [x] les supprimer d'amazon

**Comment by krichtof** [comment]
Utilisation de [s3cmd](https://s3tools.org/usage) pour récupérer les anciennes pièces jointes
