### ISSUE TITLE
organiser le bien-traîtement de nos utilisateurs

### ISSUE THREAD

**Issue by yaf** [betagouv/dossiersco#257]
Mettre en place les canaux de communication pour aider la communauté d'usagers

**Comment by yaf** [comment]
- L'an dernier, les agents appelaient directement Pierre
-

**Comment by krichtof** [comment]
Citation : "l’administration devrait systématiquement proposer un outil « permettant à l’usager de signaler une difficulté à effectuer la démarche ». Il préconise en outre l’instauration d’une « clause de protection des usagers en cas de problème technique », qui leur permettrait de ne pas être considérés comme responsables du non-aboutissement de la demande."
