### ISSUE TITLE
envoyer les invitations à s'inscrire

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/dossiersco#267]
Afin de déclencher la campagne d'inscription, l'établissment déclenche l'envoie des invitations aux parents.

dépends de #258

**Comment by LucienMLD** [comment]
duplicate #177

**Comment by krichtof** [comment]
Pas d'envoi mail d'invitation. Les établissements impriment pour chacun des classes les convocations d'inscription qui sont remises par les élèves à leurs parents
