### ISSUE TITLE
Sign in du super admin ne fonctionne plus

### ISSUE THREAD

**Issue by Pierre2Maulmont** [betagouv/dossiersco#278]
Aboutit sur message d'erreur et non sur message d'erreur de mot de passe

**Comment by yaf** [comment]
Je suppose une liaison avec la suppression de l'établissement par défaut attaché à ton identifiant.
Cela lève des exceptions sur les code sources:
- app/views/partials/_navbar_espaces_agent.html.erb
- app/controllers/inscriptions_controller.rb in liste_des_eleves at line 37

voir https://sentry.io/betagouv-pe/rails/issues/863967786/?query=is%3Aunresolved

Plusieurs questions à répondre avant de résoudre le soucis : 
- Est-ce qu'un agent à obligatoirement un établissement ?
- L'application doit absoluement avoir un agent (le premier, forcement un super admin) ET un étabque le super admin à forcement un établissementlissement (si nous considérons que c'est obligatoire pour un agent)
- Comment réagir si un établissement est supprimer alors que les agents et autres données y sont lié ? Tout supprimer quand même ? Laisser des fantomes ? Archiver l'établissement plutôt que le supprimer ?
