### ISSUE TITLE
création établissement avec un email pour l'admin de l'établissement

### ISSUE THREAD

**Issue by yaf** [betagouv/dossiersco#279]
Afin de permettre un accueil plus facile des établissements souhaitant rejoindre DossieSCO, 

- le super admin crée l'établissement
- y ajoute le courriel de l'administrateur principal
- ce dernier reçoit un courriel avec un texte d'explication et un lien lui permettant de continuer la configuration de sont établissement

**Comment by LucienMLD** [comment]
duplicate #345
