### ISSUE TITLE
s'assurer (et rassurer) que le RGPD est respecté

### ISSUE THREAD

**Issue by yaf** [betagouv/dossiersco#305]
- [ ] vérifier la conformité RGPD
- [ ] afficher sur le site les démarches mises en place et les conséquences pour les utilisatrices et utilisateurs (agents et familles)

**Comment by Pierre2Maulmont** [comment]
Sujet abordé par les kickoffeurs du 16/4 et j'aurais besoin de biscuits mardi 30/4.
