### ISSUE TITLE
tableau de bord de configuration

### ISSUE THREAD

**Issue by Pierre2Maulmont** [betagouv/dossiersco#312]
Aujourd'hui, j'écran par défaut dans le module configuration est blanc.

Nous pourrions avoir un écran avec
- des infos sur le nombre d'agent et éventuellement une incitation à en ajouter
- des infos sur les MEFs et éventuellement une invitation 
- des infos sur les options pédagogiques et éventuellement des actions à mener dessus.

La présentation pourrait être un texte avec des hyper lien qui amène vers un formulaire.

**Comment by yaf** [comment]
- [ ] ajotuer des liens vers les formulaires existant
- [ ] agencer les cartes pour mettre en avant une action particulière
