### ISSUE TITLE
Voir la pièce jointe : fonctionne avec une image, pas un pdf

### ISSUE THREAD

**Issue by Pierre2Maulmont** [betagouv/dossiersco#313]
https://demo.dossiersco.beta.gouv.fr/pieces_a_joindre

**Comment by Pierre2Maulmont** [comment]
"Voir la pièce" ne fonctionne pas non plus, côté agent

**Comment by LucienMLD** [comment]
Avec quel navigateur ? J'ai tenté de reproduire le test mais l'affichage du pdf fonctionne
