### ISSUE TITLE
Zéro option pédagogique apparait sur test Arago, écran élève

### ISSUE THREAD

**Issue by Pierre2Maulmont** [betagouv/dossiersco#315]

**Comment by yaf** [comment]
Il est possible que l'élève choisi n'est pas de _mef destination_. C'est un signalement que nous devrions faire dans le tableau de bord du suivi d'inscription (ou de configuration ?).

Pourrais tu nous donner l'identifiant de l'élève (ou les élèves) pour lesquelles les options ne s'affichent pas ?

**Comment by Pierre2Maulmont** [comment]
il s'agit de Abigael MAKAYA, INE=060446965EA
--

**Comment by krichtof** [comment]
Vu avec @Pierre2Maulmont . Effectviement, l'élève choisi n'a pas de mef destination.

**Comment by krichtof** [comment]
La mef_destination n'est pas présente car l'élève est actuellement en 1ere et notre algorithme ne sait pas pour l'instant calculer le niveau supérieur.
Je t'invite @Pierre2Maulmont à faire plutôt un test avec un-e élève en collège, tant qu'on ne connait précisément comment est constitué le code mef.
