### ISSUE TITLE
Ecran "Elève en cours de traitement" pas responsive : on ne voit pas la colonne "attestation d'assurance"

### ISSUE THREAD

**Issue by Pierre2Maulmont** [betagouv/dossiersco#316]
https://demo.dossiersco.beta.gouv.fr/agent/liste_des_eleves

- [x] arriver sur l'onglet dossier par défaut
- [x] pouvoir valider les pièces jointes dans la vue du dossier
- [x] supprimer les colonnes pièces jointes
- [x] rendre la ligne cliquable

**Comment by LucienMLD** [comment]
Le tableau a désormais une largeur figée qui tient sur un écran.
Pour ce faire, nous avons supprimé les pièces jointes du tableau, qui peuvent être désormais valider depuis la page du dossier de l'élève
