### ISSUE TITLE
contacter l'équipe technique

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/dossiersco#340]
installer drift https://app.drift.com/home

**Comment by krichtof** [comment]
A faire :

- [ ] Installer Drift
- [ ] Indiquer les heures de dispo où l'on répond en "direct"
- [ ] Rédiger le formulaire de consentement GDPR

**Comment by yaf** [comment]
Il manquerais bien une documentation pour l'équipe pour savoir où recevoir les messages ?

**Comment by yaf** [comment]
Voir une documentation (sur le site ?) pour les utilisatrices et utilisateurs
