### ISSUE TITLE
Permettre à l'agent de vérifier que la pièce téléchargée n'est pas vide ou noire, sans l'ouvrir (car fastidieux)

### ISSUE THREAD

**Issue by Pierre2Maulmont** [betagouv/dossiersco#372]
La Garriguette suggère une visualisation permanente sous forme de vignette

**Comment by yaf** [comment]
Pour certains cas, nous devrions pouvoir faire des choses automatiquement : 

Pourrait être refusé automatiquement 

- une image en couleur unis
- une image trop petite ou trop grosse pourra
- ... ?

Peut-être pourrions nous essayer de récolter les cas de refus et voir combien pourrait être traité automatiquement. Je rappel que le PDF peut-être analysé par un programme (on pourrait vérifier qu'il y a certains mots dedans et autre ?)

En gardant une validation manuelle, on pourrait faire, dans un premier temps un pré-tri, et une fois que certaines règles fonctionne bien, on automatise.

Nous avions parlé également de faire une vue spécial pour la validation des pièces jointes, en mode Tinder, avec la prévu de la pièce en pleine page, avec deux boutons pour validé ou refusé, puis ça passe à la suivante automatiquement.
