### ISSUE TITLE
préparer le message d'annonce pour la mise en production de ces changements

### ISSUE THREAD

**Issue by yaf** [betagouv/dossiersco#414]

**Comment by Pierre2Maulmont** [comment]
En fait, les collèges auxquels j'ai envoyé un mot de passe ne sont pas impactés par la feature "inscrire mon établissement", donc on peut mettre en prod sans communiquer préalablement !

**Comment by Pierre2Maulmont** [comment]
Sans attendre la solution idéale pour informer nos utilisateurs des nouvelles fonctionnalités, j'ai créé un release_note_dossiersco.md dans a_suivre et ajouté le wording sur inscription automatique

**Comment by yaf** [comment]
Dans le mouvement, nous aimerions changer le « login » pour utiliser un mot de passe maintenant... il nosu faut donc faire une communication sur ce sujet au moins.

:thinking: à moins que nous gardions ce changement pour plus tard... Nous en parlons lundi ?
