### ISSUE TITLE
Si un collège est déjà inscrit, bloquer la procédure d'inscription par l'agent pour éviter le doublon et l'en informer.

### ISSUE THREAD

**Issue by Pierre2Maulmont** [betagouv/dossiersco#421]

**Comment by yaf** [comment]
Tu as reouvert cet issue @Pierre2Maulmont parce que tu as détecté un problème ? Dans ce cas, pourrais tu nous informer en ajoutant un commentaire (sinon, nous ne voyons pas vraiment apparaitre ce ticket).

Et si c'est juste une « erreur de manip », pas de soucis, je te laisser refermer :-)
