### ISSUE TITLE
Supprimer message contenant bandeau vert sur configuration/etablissements/new

### ISSUE THREAD

**Issue by Pierre2Maulmont** [betagouv/dossiersco#430]
texte "Utilisez votre email pour vous connecter. "

**Comment by yaf** [comment]
Attention Pierre, ici tu demandes un changement, tu n'annonces pas une erreur, un comportement attendu.

J'ai supprimer le message en question, mais du coup, il n'apparait plus sur la page de login des agents. Vu les 2 emails reçu vendredi, je pense que le message n'était pas vue/lu. Ça questionne la façon dont nous pourrions parler (à notre initiative) à nos utilisateurs via l'application :thinking:
