### ISSUE TITLE
Message d'erreur sur création établissement

### ISSUE THREAD

**Issue by Pierre2Maulmont** [betagouv/dossiersco#431]
UAI : 0750123Y
message : "translation missing: fr.configuration.etablissements.create.unknown attribute 'jeton' for Agent"

**Comment by yaf** [comment]
Pourrais tu décrire l'enchainement d'écran qui t'amène à ce message ? Je n'arrive pas à refaire le cheminement : quand je vais sur l'écran de création d'établissement, et que je saisi l'UAI que tu indique pour le créer, j'ai un message : « Nous n'avons pas reconnu l'uai que vous avez renseigné »

Merci pour les informations supplémentaires que tu pourras nous fournir :)
