### ISSUE TITLE
En prod, quand le compte super admin clique sur modifier le compte de l'admin, il tombe sur le compte du super admin

### ISSUE THREAD

**Issue by Pierre2Maulmont** [betagouv/dossiersco#436]

**Comment by yaf** [comment]
Le bug, c'est de pouvoir modifier un agent qui n'est mas sois.
Le super admin ne peux pas modifier un autre agent.
La résolution passe par la suppression du lien « modifier » qui laissais croire qu'on pouvait modifier un autre agent.

Est-ce que ça te conviens ?
