### ISSUE TITLE
Permettre au collège de forcer un élève ayant une option en N-1 à la conserver

### ISSUE THREAD

**Issue by Pierre2Maulmont** [betagouv/dossiersco#458]
Ne pas laisser un élève inscrit en Allemand par exemple en 4ème, changer de langue pour la 3ème. Il faudrait pouvoir afficher la langue mais avec une impossibilité de la modifier. La même chose pour l’espagnol, pour la 6ème bilangue, etc...

**Comment by krichtof** [comment]
duplicate #487
