### ISSUE TITLE
Problème sur la visualisation de pièce jointe

### ISSUE THREAD

**Issue by Pierre2Maulmont** [betagouv/dossiersco#463]
Lorsque le super-admin veut visionner les pièces de Alexandre M, dans l'interface agent, il se retrouve sur l'interface familles de l'élève Kahina S, collège Rabelais à Metz

**Comment by Pierre2Maulmont** [comment]
URL de la page d'erreur : 
https://dossiersco.fr/uploads/Coll%C3%A8ge%20test%20PILATRE%20de%20ROZIER/piece_jointe/MAITRE/passeports_pierre.pdf

Après clic sur "retour à l'accueil", URL de la page suivante : https://dossiersco.fr/accueil
mais sur l'interface élève d'un autre collège.

Bug reproduit depuis ordi perso comme depuis ordi bureau

**Comment by yaf** [comment]
C'est pas lié à un type d'ordinateur (puisque c'est sur une interface web, et à priori non lié au type de navigateur utilisé).

Je suis en train d'investiguer, je note mes découvertes dans un fichier qu'on va partagé par ailleur.

**Comment by Pierre2Maulmont** [comment]
nouveau test ce jour, sur mon ordi et sur celui de Robi : comportement différent.

**Comment by krichtof** [comment]
Piece jointe supprimée par @yaf 
Je peux à nouveau consulter le dossier de l'élève.
Je ferme l'issue
