### ISSUE TITLE
Imprimer les fiches infirmeries

### ISSUE THREAD

**Issue by yaf** [betagouv/dossiersco#468]
Permettre au collège d'imprimer toutes/certaines des "fiches infirmerie” avec nom, prénom élève, pour traitement non numérique de l'information

En PDF.

**Comment by yaf** [comment]
Pourrait-on avoir quelques exemples ? Anonymisé ou bien dans le Keybase.

**Comment by Pierre2Maulmont** [comment]
J'en ai mis une dans keybase, etablissements, Beaumarchais

**Comment by yaf** [comment]
Merci !

**Comment by Pierre2Maulmont** [comment]
Nouvelle demande par LA FONTAINE aujourd'hui
