### ISSUE TITLE
L'option pédagogique obligatoire n'est pas proposée à la famille

### ISSUE THREAD

**Issue by Pierre2Maulmont** [betagouv/dossiersco#476]
# En tant qu'admin

J'ai créé une option obligatoire pour tous les MEF :
![image](https://user-images.githubusercontent.com/20454258/55085755-7b4e4b80-50a7-11e9-96ed-f4d14642f5ce.png)

# En tant que famille

Elle n'est pourtant pas proposée : 
![image](https://user-images.githubusercontent.com/20454258/55085853-a3d64580-50a7-11e9-9632-10a22bad32ce.png)

**Comment by yaf** [comment]
Je n'arrive pas à reproduire ce bug. Est-ce qu'il a été corrigé par un effet de bord ? Est-ce que l'élève et les liens mefs-options-élève sont ok ?

**Comment by LucienMLD** [comment]
Je n'arrive pas à reproduire non plus
