### ISSUE TITLE
Impossible d'uploader le règlement intérieur de la demi-pension

### ISSUE THREAD

**Issue by Pierre2Maulmont** [betagouv/dossiersco#478]
"Bonjour ! Suite à une erreur technique, DossierSCO ne peut pas satisfaire votre demande pour l'instant. Nous sommes désolés de ce contre-temps."

https://sentry.io/organizations/betagouv-pe/issues/?project=1368768&statsPeriod=14d&utc=true

**Comment by LucienMLD** [comment]
il manquait une migration sur la démo
