### ISSUE TITLE
Coté agent, un élève inscrit a le même MEF d'origine et de destination

### ISSUE THREAD

**Issue by Pierre2Maulmont** [betagouv/dossiersco#480]
https://dossiersco-demo.scalingo.io/agent/eleve/110812816JB : 
MEF : 6ème et 6ème

![image](https://user-images.githubusercontent.com/20454258/55089918-80fb5f80-50ae-11e9-8f78-1a49373ef654.png)

**Comment by yaf** [comment]
Corrigé par l'ajout d'une options « aucune » pour les cas où nous n'avons pas trouver de mef (origine ou destination).

Je garde le ticket dans la colonne projet « en cours » le temps de vérifier en situation que la solution convient)
