### ISSUE TITLE
Connaitre le degré d'implication des établissements

### ISSUE THREAD

**Issue by krichtof** [betagouv/dossiersco#483]
En tant que superadmin, je veux pouvoir afficher la liste et le nombre d'établisssements :

- qui ne se sont pas encore connectés
- qui ont déjà importé leurs élèves
- qui ont ajouté des pièces attendues
- qui ont déjà des familles qui se sont connectés

**Comment by yaf** [comment]
Est-ce qu'on peut envisager d'afficher publiquement le nombre d'établissement à chaque étape et, l'accès au détail (liste des noms d'établissement) accessible uniquement aux superadmin ? @krichtof @Pierre2Maulmont

**Comment by yaf** [comment]
https://dossiersco.fr/suivi

**Comment by yaf** [comment]
https://github.com/betagouv/dossiersco/commit/e98f514e1343f535483b9870a05f2cc29279aa0b

**Comment by yaf** [comment]
Je me demande si les données utilisé pour ce suivi sont pertinantes. Nous pourrons en reparler et itérer sur cette base.

Reste à faire le point de détail (lister les établissements). On re-ouvre ce ticket où bien on en fait un autre, une fois les chiffres bien réfléchi ?

**Comment by krichtof** [comment]
@yaf ok pour discuter du bien-fondé des données choisies.
Initialement, le cas d'usage pour ce ticket est de savoir rapidement pour le superadmin quels établissements appeler en fonction de son degré d'embarquement. Sans la liste des établissements, c'est assez peu actionnable. Je réouvre donc le ticket.
