### ISSUE TITLE
Franciser le message qui indique qu'une option pédagogique a été sauvegardée

### ISSUE THREAD

**Issue by krichtof** [betagouv/dossiersco#484]

**Comment by yaf** [comment]
Je ne vois pas l'endroit ou le message qui pose problème ? Est-ce que tu pourrais nous donner quelques informations complémentaires ?

Merci !

**Comment by krichtof** [comment]
Je ne le vois pas non plus. J'ai l'impression que la nouvelle façon de gérer les options a réglé le pb. Je clôture donc :)
