### ISSUE TITLE
Informer la famille des implications du choix d'une option pédagogique

### ISSUE THREAD

**Issue by Pierre2Maulmont** [betagouv/dossiersco#486]

**Comment by yaf** [comment]
Besoin d'un peu plus d'informations.

Est-ce un email récapitulatif ? Un écran ? Des textes à coté des options ? Comment configurer les textes ? Est-ce en dur dans l'application ou bien configurable par les agents (admin ou pas ?) ?

**Comment by Pierre2Maulmont** [comment]
Texte configurable par l'agent.
