### ISSUE TITLE
Configurer l'abandonnabilité d'une option

### ISSUE THREAD

**Issue by Pierre2Maulmont** [betagouv/dossiersco#487]
En tant qu'admin d'un établissement, je peux décider du caractère abandonnable d'une option, pour un MEF donné.
ex: pour une élève de 5ème passant en 4ème, si l'option Latin déjà choisie en 5ème est abandonnable en 4ème, les parents peuvent la décocher ; sinon, l'option latin apparait déjà cochée et grisée

**Comment by yaf** [comment]
Nous pourrions en profiter pour reprendre les interfaces MEF et Option Pédagogiques : 
- les MEF pourraient être créé à partir de l'écran des options
- les options seraient présenté par MEF, et configuré par MEF

l'écran par défaut de la configuration des options serait

**Comment by Pierre2Maulmont** [comment]
L'écran MEF contenant des options

**Comment by yaf** [comment]
revoir navigation de configuration des options / MEF : 
- [ ] un truc pour aller sur un formulaire de création de options
- [ ] un truc pour aller sur un formulaire de création de mef
- [ ] un truc pour aller sur un formulaire de mise à jour d'une option
- [ ] un truc pour aller sur un formulaire de mise à jour d'un mef
- [ ] un seul écran pour option et mef dans lequel on fait la configuration des options par mef

Configuration de regles pour l'abandonnabilités d'option par mef
- [ ] griser les options qu'on ne peux pas changer dans l'interface famille

**Comment by yaf** [comment]
Est-ce que l'écran tel que nous l'avons fait est satisfaisant ? Peut-être pas pour toutes les règles ...

Comment définir les règles ?

Comment associé les règles au bon niveau de granularité (passage d'un mef à l'autres ? option isolé ?, ...)

**Comment by yaf** [comment]
Note technique : 
- [ ] supprimer les anciennes tables et classes autour des options pédago et montée/demandabilité ...
- [ ] créer une classe montée_pédagogique pour stocker un mef origine, un mef destination, une option pédago, et la règle sur l'abandonnabilitée (pour mef dest et origine, voir dossier_eleve)
- [ ] supprimer la jointure HABTM(Has And Belongs To Many) mef <-> options pédago (dans les deux classe)
- [ ] revoir l'import SIECLE
- [ ] ajouter un champ  [json hash sérialisé ou juste texte avec hash sérialisé] avec id, code et nom des options pédagogique de l'année dernière dans le dossier_eleve.


_note : https://stackoverflow.com/questions/6694432/using-rails-serialize-to-save-hash-to-database_

**Comment by LucienMLD** [comment]
#504
