### ISSUE TITLE
Revoir le wording des messages aux parents, à la fin de procédure d'inscription

### ISSUE THREAD

**Issue by Pierre2Maulmont** [betagouv/dossiersco#499]
Lorsque les pièces attendues ne sont pas conformes, les familles se considèrent inscrites quand même et il est difficile de les mobiliser pour qu'elles transfèrent à nouveau.
Les messages de fin d'inscription laissent croire que l'inscription est terminée :
"Le dossier d'inscription de votre enfant Cécile AAAAA pour son entrée en 3ème au collège xxx est complet. Veuillez vérifier les informations ci-dessous, puis validez l'inscription."
"Réinscription validée. Vous recevrez prochainement un courriel de confirmation aux adresses suivantes :"

Il faudrait renforcer sur le fait que l'inscription est EN COURS, même si la première phase est terminée.

Je propose : "Réinscription enregistrée. L'inscription ne sera validée qu'à réception d'un email de confirmation aux adresses suivantes :"

**Comment by Pierre2Maulmont** [comment]
"Veuillez vérifier les informations ci-dessous, puis validez l'inscription."
https://demo.dossiersco.fr/validation

**Comment by yaf** [comment]
Est-ce qu'il est possible de préciser un peu plus pourquoi ce ticket à été re-ouvert ?

J'envisage que : la solution en place n'est pas suffisante; mais en l'état, je ne sais pas ce qui pose problème.

Merci d'avance !
