### ISSUE TITLE
L'envoi par défaut des mails à pierre.de-maulmont@ac-paris.fr va gêner la conversion

### ISSUE THREAD

**Issue by Pierre2Maulmont** [betagouv/dossiersco#523]
https://dossiersco.fr/configuration/etablissements/248
Lorsque la case "Activer l'envoi aux familles" est décochée, les message suivant apparait : "Les envois de messages que vous déclencherez seront envoyé à l'email pierre.de-maulmont@ac-paris.fr ".
Pour un principal pas convaincu d'utiliser DossierSCO, ça rebute. Solution : remplacer par l'adresse ce.UAI@ac-Nom_de_mon_académie.fr

**Comment by LucienMLD** [comment]
@Pierre2Maulmont  Il me semble que c'est déjà le cas. Tu vois ton adresse car on l'a créée manuellement. Pour un collège qui s'inscrit seul les emails sont envoyés à ce.UAI@ac-Nom_de_mon_académie.fr
