### ISSUE TITLE
L'UAI du collège TILLION apparaît dans l'interface Agents de la démo

### ISSUE THREAD

**Issue by Pierre2Maulmont** [betagouv/dossiersco#524]
Pour une anonymisation totale, mieux vaudrait ne pas employer ce numéro unique d'établissement et employer un n° fictif, genre : 0750001A
https://demo.dossiersco.fr/agent/tableau_de_bord

**Comment by LucienMLD** [comment]
@Pierre2Maulmont moi je vois 0753936W comme UAI quand je me connecte avec l'agent de test

**Comment by Pierre2Maulmont** [comment]
Oui et c'est l'UAI de Tillion.

**Comment by LucienMLD** [comment]
Autant pour moi j'en ai mis un autre qui ne correspond à aucun collège
