### ISSUE TITLE
La fonction Ajout d'une nouvelle option, sur espace démo, est introuvable

### ISSUE THREAD

**Issue by Pierre2Maulmont** [betagouv/dossiersco#525]
https://demo.dossiersco.fr/configuration/options_pedagogiques

**Comment by LucienMLD** [comment]
@Pierre2Maulmont avec @yaf on avait compris qu'il n'y avait pas besoin de la fonctionnalité d'ajout d'une option. C'est pour ça qu'il n'y a plus le lien
