### ISSUE TITLE
Automatiser la création de la charte d'adhésion

### ISSUE THREAD

**Issue by Pierre2Maulmont** [betagouv/dossiersco#533]
Avec :
- Les deux Mariane DINSIC et MEN en en-tête
- nom du collège et de son principal en signature

https://hackmd.io/olwFrccLQWCdnP6bZ0lQvQ?both

**Comment by yaf** [comment]
Est-ce qu'on parle ici d'un texte avec case à coché lors de l'inscription d'un établissement ?

Comment allons nous faire pour ceux déjà inscrit ?
