### ISSUE TITLE
Importer un fichier ZIP qui contient un fichier XML

### ISSUE THREAD

**Issue by yaf** [betagouv/dossiersco#614]
SIECLE exporte les fichiers XML dans un zip.

Si DossierSCO pouvais prendre un fichier ZIP en entrée, ça simplifierais les manipulations pour les utilisateurs.

**Comment by yaf** [comment]
Après test, cela ne semble pas fonctionner aussi bien que j'avais cru.

**Comment by pblayo** [comment]
Suite à discussion avec @yaf cette nuit, je baisse la priorité de l'import des zip malgré l'énorme amélioration que cela procurerait en terme d'expérience utilisateur. Les deux régressions bloquantes observées ces derniers jours autour de cette story plaident pour différer sa mise en production d'une semaine ou deux. Ca n’empêche pas de travailler dessus sur une branche à part.
