### ISSUE TITLE
Permettre de poursuivre quand des élèves n'ont pas de division affectée

### ISSUE THREAD

**Issue by yaf** [betagouv/dossiersco#615]
Suite à l'import du fichier EleveAvecAdresse.xml, nous avons normalement une divsion pour chaque dossier.

Si un élève est sans division, nous sommes bloqué dans le retour siecle.

Pour débloquer la situation, il faudra proposer un lien vers la page du dossier et permettre de mettre à jour manuellement la division de l'elève (page dossier, onglet MEF et options)

**Comment by pblayo** [comment]
Pour reproduire le problème : 
- 1/ recréer Arago avec la base /keybase/team/dossiersco/retour_dans_siecle/arago_2018_2019/ElevesComplete.xls
- 2/ dans "retour vers siecle", importer /keybase/team/dossiersco/retour_dans_siecle/arago_2019_2020/Nomenclature.xml.
- 3/ Réaliser l'import pour ElevesAvecAdresses.xml
Problème : un élève, dont le prénom se termine par un - (tiret) reste sans division. Il n'est pas possible de faire un retour siecle car il n'est pas possible de renseigner une division dans DossierSCO
