### ISSUE TITLE
Rendre explicite les étapes du retour siecle : préparation, export

### ISSUE THREAD

**Issue by pblayo** [betagouv/dossiersco#620]

**Comment by yaf** [comment]
Aujourdh'ui, le menu « retour base élève » n'est qu'un seul controller;
Ce controller a une seule action qui, en fonction de ce qu'il se passe à certain niveau, affiche une vue qui dit qu'il manque un truc.

L'idée serais de dire ce qu'on va faire avec une série de page, peut-être un chemin de fer (breadcrumb ?) qui dit:
« là on vérifie les code matière sur les options » Quitte à dire : rien à signaler, passer à l'étape suivante
« là on vérifie les divisions » quitte à dire : rien à signaler, passer à l'étape suivante.

Peut-être aussi qu'on peut faire un passage automatique à l'étape à traiter, mais afficher les étapes précédentes 

aujourd'hui, elles sont masqué, c'est pas top

Le but est de rendre visible les différentes étapes.
