### ISSUE TITLE
Ne pas afficher les code mef manquant avant un 1er import de nomenclature

### ISSUE THREAD

**Issue by pblayo** [betagouv/dossiersco#624]
Risque de suppression de code mef avant import de nomenclature :
- changer le titre en "N options incomplètes pour siecle, veuillez importer Nomenclature.xml"

**Comment by yaf** [comment]
Dans la page du flux de «retour base élève », l'affichage de la règle « code matière manquant, importé votre fichier nomenclature.xml » est lié à l'analyse des code matières, pas du fait que le fichier nomenclature.xml a été chargé ou pas.

Le tableau qui liste les codes à problème pourrais ne pas être affiché tant que le fichier nomenclature n'a pas été chargé.
