### ISSUE TITLE
compléter le fichier d'export des changements

### ISSUE THREAD

**Issue by yaf** [betagouv/dossiersco#644]
Nous avons ajouté l'export d'un fichier permettant de lister les dossiers et les changements d'adresses des responsables légaux.

Dans un email, un gestionnaire nous demande  
- [x] d'ajouter les emails
- [x] d'ajouter les téléphones
- [x] de revoir les adresses. Suite à une fusion de commune, dans siecle, les anciennes communes sont sur la deuxième ligne d'adresse. Dans DossierSCO, tout est tassé sur une ligne.

Pour plus de précision, voir le message de Vincent Bardaud, reçu le lundi 30 septembre à 10h20.

**Comment by krichtof** [comment]
Livré le 2/10. Le nouveau fichier fait très bien l'affaire pour le collège Boris Vian.
