### ISSUE TITLE
Erreur au build

### ISSUE THREAD

**Issue by vvatelot** [betagouv/dossiersco#651]
En lançant la commande `make build` voilà l'erreur que j'obtiens :  
```
Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown
make: *** [Makefile:10: build] Error 1
```

**Comment by yaf** [comment]
Merci pour ce signalement !

Est-ce que Docker est installé sur ta machine ?

**Comment by vvatelot** [comment]
Oui, docker et docker-compose bien installés : 
```
Docker version 19.03.2, build 6a30dfc
docker-compose version 1.23.1, build b02f1306
```

**Comment by yaf** [comment]
J'ai les même versions de docker et docker-compose, et je n'arrive pas à reproduire l'erreur. Peut-être que j'ai mal nettoyé le cache docker.  Est-ce lié à la machine que tu utilises ?

**Comment by vvatelot** [comment]
@yaf, je suis sur fedora 30.
Je relance un build en faisant un gros ménage dans mes containers, images et volumes...

**Comment by krichtof** [comment]
Bonjour @vvatelot . Est que le ménage a porté ses fruits ?

Sinon, sais-tu à quel moment tu as l'erreur ?
```make build``` lance cette commande : 

```docker-compose build && docker-compose run --rm app bash -c "bundle install && rails db:migrate"```

Est-ce que ```docker-compose build``` se passe bien ? ou est-ce ensuite lors du ```docker-compose run --rm app bash -c "bundle install && rails db:migrate"```

**Comment by vvatelot** [comment]
Désolé pour le délai de réponse... Oui, le build se passe bien. C'est lors du `bundle install` que j'ai un souci :
```
$ docker-compose run --rm app bash -c "bundle install && rails db:migrate" 
Creating network "dossiersco_default" with the default driver
Creating dossiersco_postgres_1_de846608ee42 ... done
Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown
```
